# Generated by Django 4.0.2 on 2022-03-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Group Information',
                'verbose_name_plural': 'Group Information',
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Papers',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='PaperList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='papername')),
                ('is_allow', models.BooleanField(default=False, verbose_name='if_tested')),
            ],
            options={
                'verbose_name': 'PaperList',
                'verbose_name_plural': 'PaperList',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='QuestionDescription')),
                ('equation', models.TextField(verbose_name='QuestionEquation')),
                ('answer', models.TextField(verbose_name='RightAnswer')),
                ('choice_a', models.CharField(default='A.', max_length=32, verbose_name='ChoiceA')),
                ('choice_b', models.CharField(default='B.', max_length=32, verbose_name='ChoiceB')),
                ('choice_c', models.CharField(default='C.', max_length=32, verbose_name='ChoiceC')),
                ('choice_d', models.CharField(default='D.', max_length=32, verbose_name='ChoiceD')),
                ('score', models.IntegerField(default=0, verbose_name='Marks')),
                ('note', models.TextField(default='Answer: ', verbose_name='CandidateAnswer')),
                ('boolt', models.CharField(default='True', max_length=32, verbose_name='DetermineTrue')),
                ('boolf', models.CharField(default='False', max_length=32, verbose_name='DeterminFalse')),
            ],
            options={
                'verbose_name': 'questions',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='usersprofile',
            fields=[
                ('id', models.AutoField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('usertype', models.CharField(max_length=32)),
                ('emailAddress', models.CharField(max_length=32)),
                ('groupNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGroup', to='CNExplorer.groups')),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Information',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='CandidateAnswer')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.paper', verbose_name='Paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.usersprofile', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'UserResult',
                'verbose_name_plural': 'UserResult',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='paperName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.paperlist', verbose_name='PaperName'),
        ),
        migrations.AddField(
            model_name='paper',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.question', verbose_name='Question'),
        ),
    ]
