# Generated by Django 4.0.2 on 2022-03-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=32)),
                ('groupCode', models.CharField(default='', max_length=32)),
            ],
            options={
                'verbose_name': 'Group Information',
                'verbose_name_plural': 'Group Information',
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='QuestionDescription')),
                ('equation', models.TextField(verbose_name='QuestionEquation')),
                ('answer', models.TextField(verbose_name='RightAnswer')),
            ],
            options={
                'verbose_name': 'questions',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='usersprofile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
                ('usertype', models.CharField(max_length=32)),
                ('emailAddress', models.CharField(max_length=32)),
                ('groupNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGroup', to='CNExplorer.groups')),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Information',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PaperList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='papername')),
                ('is_allow', models.BooleanField(default=False, verbose_name='if_tested')),
                ('groupNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_Group', to='CNExplorer.groups')),
            ],
            options={
                'verbose_name': 'PaperList',
                'verbose_name_plural': 'PaperList',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PaperListID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.paperlist', verbose_name='PaperName')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Papers',
                'verbose_name_plural': 'Papers',
            },
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(verbose_name='CandidateAnswer')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.paperlist', verbose_name='Paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNExplorer.usersprofile', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'CandidateResult',
                'verbose_name_plural': 'CandidateResult',
            },
        ),
    ]
