# Generated by Django 4.0.2 on 2022-03-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='password',
        ),
    ]
