# Generated by Django 4.0.2 on 2022-03-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDatabase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='QuestionDescription')),
                ('equation', models.TextField(verbose_name='QuestionEquation')),
                ('answer', models.TextField(verbose_name='RightAnswer')),
            ],
            options={
                'verbose_name': 'QuestionDatabase',
                'verbose_name_plural': 'QuestionDatabase',
            },
        ),
    ]
