# Generated by Django 4.0.2 on 2022-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0002_remove_usersprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
