# Generated by Django 4.0.2 on 2022-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0003_paperlist_is_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperlist',
            name='startQuestionID',
            field=models.CharField(default='', max_length=32),
        ),
    ]
