# Generated by Django 4.0.2 on 2022-03-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0003_alter_usersprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='groupNum',
            field=models.CharField(max_length=32),
        ),
    ]
