# Generated by Django 4.0.2 on 2022-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0004_alter_usersprofile_groupnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='groupNum',
            field=models.IntegerField(default=0, verbose_name='groupNum'),
        ),
    ]
