# Generated by Django 4.0.2 on 2022-03-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0006_alter_usersprofile_groupnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_d',
        ),
    ]
