# Generated by Django 4.0.2 on 2022-03-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CNExplorer', '0007_delete_groups_remove_question_choice_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
